name: CI

on:
  push:
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: git clone --recurse-submodules https://git.ardour.org/ardour/ardour.git -b 7.0
      - name: deps
        run: sudo apt install -y git autoconf automake libtool pkg-config yasm python gettext libboost-all-dev alsa-base libasound2 libasound2-dev libpulse-dev libsndfile1-dev libglibmm-2.4-dev libcurl4-openssl-dev libarchive-dev liblo-dev libtag1-dev vamp-plugin-sdk librubberband-dev libudev-dev libfftw3-dev libjack-dev libaubio-dev
      - name: configure
        working-directory: ardour
        run: ./waf configure
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            x86_64-w64-mingw32-openssl
            x86_64-w64-mingw32-toolchain
            python3
            python3-setuptools
            x86_64-w64-mingw32-python3
            x86_64-w64-mingw32-python3-setuptools
            pkg-config
            x86_64-w64-mingw32-pkg-config
            autoconf
            automake
            perl
            gtk-doc
            flex
            bison
            patch
            libtool
            x86_64-w64-mingw32-libtool
            wget
            git
            nasm
            x86_64-w64-mingw32-nasm
            dos2unix
            x86_64-w64-mingw32-cmake
            x86_64-w64-mingw32-glib2
            x86_64-w64-mingw32-gobject-introspection
            x86_64-w64-mingw32-pkg-config
            x86_64-w64-mingw32-c-ares
            x86_64-w64-mingw32-ca-certificates
            x86_64-w64-mingw32-gnutls
            x86_64-w64-mingw32-libidn
            x86_64-w64-mingw32-libssh2
            x86_64-w64-mingw32-rtmpdump
            x86_64-w64-mingw32-gnutls
            libgnutls-devel
            libutil-linux-devel
            gtk-doc
            x86_64-w64-mingw32-docbook-xsl
            intltool
            x86_64-w64-mingw32-libjpeg-turbo
            x86_64-w64-mingw32-jbigkit
            x86_64-w64-mingw32-ladspa-sdk
            x86_64-w64-mingw32-icu
            x86_64-w64-mingw32-boost
            x86_64-w64-mingw32-curl
            x86_64-w64-mingw32-fftw
            x86_64-w64-mingw32-libusb
            x86_64-w64-mingw32-libxml2
            x86_64-w64-mingw32-libogg
            x86_64-w64-mingw32-flac
            x86_64-w64-mingw32-libvorbis
            x86_64-w64-mingw32-libsndfile
            x86_64-w64-mingw32-libsamplerate
            x86_64-w64-mingw32-soundtouch
            x86_64-w64-mingw32-wineditline
            x86_64-w64-mingw32-pcre
            x86_64-w64-mingw32-cppunit
            x86_64-w64-mingw32-taglib
            x86_64-w64-mingw32-dlfcn
            x86_64-w64-mingw32-gobject-introspection
            x86_64-w64-mingw32-gtk-doc
            x86_64-w64-mingw32-gnome-common
            x86_64-w64-mingw32-atk
            x86_64-w64-mingw32-libpng
            x86_64-w64-mingw32-harfbuzz
            x86_64-w64-mingw32-cairo
            x86_64-w64-mingw32-fontconfig
            x86_64-w64-mingw32-freetype
            x86_64-w64-mingw32-pixman
            x86_64-w64-mingw32-pango
            x86_64-w64-mingw32-libjpeg-turbo
            x86_64-w64-mingw32-jasper
            x86_64-w64-mingw32-libtiff
            x86_64-w64-mingw32-shared-mime-info
            x86_64-w64-mingw32-gtk2
            x86_64-w64-mingw32-libsigc++
            x86_64-w64-mingw32-cairomm
            x86_64-w64-mingw32-glibmm
            x86_64-w64-mingw32-atkmm
            x86_64-w64-mingw32-pangomm
            x86_64-w64-mingw32-gtkmm
            x86_64-w64-mingw32-rubberband
            x86_64-w64-mingw32-vamp-plugin-sdk
            x86_64-w64-mingw32-meson
            x86_64-w64-mingw32-giflib
            x86_64-w64-mingw32-libexif
            x86_64-w64-mingw32-expat
            x86_64-w64-mingw32-libffi
            x86_64-w64-mingw32-gettext
            x86_64-w64-mingw32-fribidi
            x86_64-w64-mingw32-libepoxy
            x86_64-w64-mingw32-libgnurx
            x86_64-w64-mingw32-ncurses
            x86_64-w64-mingw32-gdk-pixbuf2
            x86_64-w64-mingw32-libgdiplus
            x86_64-w64-mingw32-libarchive
      - name: clone
        run: git clone --recurse-submodules https://git.ardour.org/ardour/ardour.git -b 7.0
      - name: compile
        working-directory: ardour
        env:
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
          CPP: x86_64-w64-mingw32-cpp
          AR: x86_64-w64-mingw32-ar
          LD: x86_64-w64-mingw32-ld
          NM: x86_64-w64-mingw32-nm
          AS: x86_64-w64-mingw32-as
          STRIP: x86_64-w64-mingw32-strip
          WINRC: x86_64-w64-mingw32-windres
          RANLIB: x86_64-w64-mingw32-ranlib
          DLLTOOL: x86_64-w64-mingw32-dlltool
        run: |
          ./waf configure --dist-target=mingw --ptformat --optimize --windows-vst --with-backends=jack,portaudio,dummy
          ./waf -j 2
          ./waf i18n
