name: CI

on:
  push:
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: git clone https://git.ardour.org/ardour/ardour.git -b 7.0
      - name: deps
        run: sudo apt install -y git autoconf automake libtool pkg-config yasm python gettext libboost-all-dev alsa-base libasound2 libasound2-dev libpulse-dev libsndfile1-dev libglibmm-2.4-dev libcurl4-openssl-dev libarchive-dev liblo-dev libtag1-dev vamp-plugin-sdk librubberband-dev
      - name: configure
        working-directory: ardour
        run: ./waf configure
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: git clone https://git.ardour.org/ardour/ardour.git -b 7.0
      - name: deps
        run: sudo apt install -y git autoconf automake libtool pkg-config yasm python gettext mingw-w64 mingw-w64-tools
      - name: get boost
        run: |
          git clone --recursive https://github.com/boostorg/boost.git -b boost-1.80.0
          cd boost
          ./bootstrap.sh
          echo "using gcc :  : x86_64-w64-mingw32-g++ ;" > user-config.jam
          ./bootstrap.sh
          ./b2 --user-config=./user-config.jam --prefix=./boost-x64 target-os=windows address-model=64 variant=release install
      - name: compile
        working-directory: ardour/tools/x-win
        run: XARCH=x86_64 ./compile.sh
